name: Générer les listes de fichiers

on:
  workflow_dispatch:   # <-- déclenchement manuel uniquement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le repo
        uses: actions/checkout@v3

      - name: Rendre le script exécutable
        run: chmod +x generer_liste_fichiers.sh

      - name: Exécuter le script
        run: ./generer_liste_fichiers.sh

      - name: Commit des fichiers générés
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Mise à jour manuelle des listes de fichiers" || echo "Aucun changement"
          git push
