name: Make search index

on:
  workflow_dispatch:   # d√©clenchement manuel uniquement

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate docs.js
        run: |
          python3 make_search_index.py

      - name: Commit docs.js
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add docs.js
          git commit -m "Update search index"
          git push
